config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root "restaurants#index"
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]
  end
  
  resources :categories, only: :show

  namespace :admin do
    root "restaurants#index"
    resources :restaurants
    resources :categories
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  has_many :restaurants, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name
  belongs_to :category, optional: true
  has_many :comments
  mount_uploader :image, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
  has_many :restaurants, through: :comments
  mount_uploader :avatar, AvatarUploader
  validates_presence_of :name

  def admin?
    self.role == "admin"
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_admin

  private
  def authenticate_admin
    unless current_user.admin?
      flash[:alert] = "Not allow!"
      redirect_to root_path
    end
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:update, :destroy]

  def index
    @categories = Category.all
    
    if params[:id]
      set_category
    else
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        flash[:notice] = "Great!"
        redirect_to admin_categories_path
      else
        @categories = Category.all
        flash.now[:alert] = "Oops! We have some errors here!"
        render :index
      end
    end

    def update
      if @category.update(category_params)
        flash[:notice] = "Category was updated successfully."
        redirect_to admin_categories_path
      else
        @categories = Category.all
        render :index
      end
    end

    def destroy
      @category.destroy
      redirect_to admin_categories_path
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end

end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController
  before_action :set_restaurant, only: [:edit, :update, :show, :destroy]
  
  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "Restaurant was created successfully."
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "Restaurant was failed to create."
      render :new
    end
  end

  def edit
    
  end

  def update
    if @restaurant.update(restaurant_params)
      flash[:notice] = "Restaurant was updated successfully."
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "There was some errors."
      render :edit
    end
  end

  def show

  end

  def destroy
    @restaurant.destroy
    flash[:alert] = "Restaurant was deleted successfully."
    redirect_to admin_restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :tel, :address, :opening_hours, :description, :image, :category_id)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @restaurants = @category.restaurants.page(params[:page]).per(9)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = @restaurant.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!
    redirect_to restaurant_path(@restaurant) 
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = Comment.find(params[:id])

    if current_user.admin?
      @comment.destroy
      redirect_to restaurant_path(@restaurant)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @comment = Comment.new
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @commented_restaurants = @user.restaurants.uniq    
  end

  def edit
    unless @user == current_user
      redirect_to user_path(@user)
    end
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/categories/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h1>餐廳分類</h1>
      <div>
        <%= link_to "Restaurant", admin_restaurants_path %> |
        <%= link_to "Category", admin_categories_path %>
      </div>
      <br>
      <div class="form-inline">
        <%= form_for [ :admin, @category ] do |f| %>
        <div class="form-group">
          <%= f.text_field :name, placeholder: "Category Name", class: "form-control" %>
        </div>
        <%= f.submit class: "btn btn-primary" %>
        <% if @category.errors.any? %>
          <%= @category.errors.full_messages.to_sentence %>
        <% end %>
        <% end %>
      </div>
      <br>
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>#</th>
            <th>Categories</th>
            <th>#</th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
          <tr>
            <th scope="row"><%= category.id %></th>
            <td><%= category.name %></td>
            <td>
              <%= link_to 'Edit', admin_categories_path(id: category.id) %> |
              <%= link_to 'Delete', admin_category_path(category), method: :delete %>
            </td>  
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/restaurants/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <% if @restaurant.errors.any? %>
      <ul>
        <h2>We have some errors here!</h2>
        <% @restaurant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <hr>
      <% end %>

      <%= form_for [:admin, @restaurant] do |f| %>
        <div class="form-group">
          <%= f.collection_select :category_id, Category.all, :id, :name, { prompt: "true" }, {class: "form-control" } %> 
        </div>
        <div class="form-group">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, placeholder: "name", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :tel, "Tel" %>
          <%= f.text_field :tel, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :address, "Address" %>
          <%= f.text_field :address, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :opening_hours, "Opening Hours" %>
          <%= f.text_field :opening_hours, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :description, "Description" %>
          <%= f.text_area :description, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :image, "Photo" %>
          <%= image_tag @restaurant.image, width: '300px' if @restaurant.image? %>
          <%= f.file_field :image %>
        </div>
        <div class="form-group">
          <%= f.submit class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/restaurants/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h2>Update Restaurant</h2>
    </div>
  </div>
  <%= render "form" %>
</div>

app/views/admin/restaurants/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h1>餐廳後台</h1>
      <div>
        <%= link_to "Restaurant", admin_restaurants_path %> |
        <%= link_to "Category", admin_categories_path %>
      </div>
      <div>
        <%= link_to "New Restaurant", new_admin_restaurant_path, class: "btn btn-primary" %>
      </div>
      <br>
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>#</th>
            <th>Category</th>
            <th>Name</th>
            <th>#</th>
          </tr>
        </thead>
        <tbody>
          <% @restaurants.each do |restaurant| %>
          <tr>
            <th scope="row"><%= restaurant.id %></th>
            <td><%= restaurant.category.name %></td>
            <td><%= restaurant.name %></td>
            <td>
              <%= link_to 'Show', admin_restaurant_path(restaurant) %>
              <%= link_to 'Edit', edit_admin_restaurant_path(restaurant) %>
              <%= link_to 'Delete', admin_restaurant_path(restaurant),
                                        method: :delete %>         
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="text-center">
        <%= paginate @restaurants %>
      </div>
    </div>
  </div>
</div>

app/views/admin/restaurants/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h2>Create New Restaurant</h2>
    </div>
  </div>
  <%= render "form" %>
</div>

app/views/admin/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1><%= @restaurant.name %></h1>
      <h4><%= @restaurant.category.name %></h4>
    </div>
    <div class="col-md-4">
      <%= image_tag @restaurant.image, class: "img-responsive center-block" if @restaurant.image? %>
      <br>
      <div class="well">
        <ul class="list-unstyled">
          <li><strong>Tel: </strong><%= @restaurant.tel %></li>
          <li><strong>Address: </strong><%= @restaurant.address %></li>
          <li><strong>Opening hours: </strong><%= @restaurant.opening_hours %></li>
        </ul>
      </div>
    </div>
    <div class="col-md-8">
      <%= simple_format @restaurant.description %>
    </div>
    <div class="clearfix"></div>
    <hr>
  </div>
  <%= link_to "Back", admin_restaurants_path %>
</div>

app/views/categories/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <ul class="nav nav-pills nav-pills-center">
        <li role="presentation">
          <%= link_to '餐廳總表', root_path %>
        </li>
        <% @categories.each do |category| %>
          <li role="presentation" class="<%= "active" if category == @category %>">
            <%= link_to category.name, category_path(category) %>
          </li>
        <% end %>
      </ul>
      <br>
      <%= render partial: "shared/restaurant_list" %>
    </div> 
  </div>
</div>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= notice %>
      </div>
    </div>
  </div>
</div>
<% end %>

<% if flash[:alert] %>
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= alert %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Restaurant Forum', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <% if current_user.admin? %>
            <li><%= link_to "Admin後台", admin_restaurants_path %></li>
          <% end %>
          <li><p class="navbar-text">Hi, <%= current_user.email %></p></li>
          <li><%= link_to "Profile", user_path(current_user) %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Edit", edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <li><%= link_to "Sing up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantForumone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/flash' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <ul class="nav nav-pills nav-pills-center">
        <li role="presentation"><%= link_to '餐廳總表', root_path %></li>
        <% @categories.each do |category| %>
          <li role="presentation"><%= link_to category.name, category_path(category) %></li>
        <% end %>
      </ul>
      <br>
      <% @restaurants.each do |restaurant| %>
        <div class="col-sm-6 col-md-4">
          <div class="restaurant-item">
            <%= image_tag restaurant.image, class: "img-responsive center-block" if restaurant.image? %>
            <div class="caption">
              <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
              <p class="label label-default"><%= restaurant.category.name %></p>
              <p><%= truncate(restaurant.description, length: 80) %></p>
            </div>
          </div>
        </div>
      <% end %>
      <div class="center">
        <%= paginate @restaurants %>
      </div>
    </div> 
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h3><%= @restaurant.name %></h3>
      <p><%= @restaurant.category.name %></p>
      <div class="col-md-4">
        <%= image_tag @restaurant.image, class: "img-responsive block-center" if @restaurant.image? %>
        <br> 
        <div class="well">
          <ul class="list-unstyled">
            <li><strong>Tel: </strong><%= @restaurant.tel %></li>
            <li><strong>Opening Hours: </strong><%= @restaurant.opening_hours %></li>
            <li><strong>Address: </strong><%= @restaurant.address %></li>
          </ul>
        </div>
      </div>
      <div class="col-md-8">
        <%= simple_format @restaurant.description %>
      </div>
    </div>
    <div class="clearfix"></div>
    <hr>
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <% @restaurant.comments.each do |comment| %>
          <h4><%= comment.user.name if comment.user %></h4>
          <p><%= simple_format comment.content %></p>
          <p class="text-muted">
            <em><%= time_ago_in_words(comment.created_at) %></em> -
            <% if current_user.admin? %>
              <%= link_to 'Delete', restaurant_comment_path(@restaurant, comment), method: :delete %>
            <% end %>
          </p>
          
          <hr>
        <% end %>
      </div>
      <div class="col-md-10 col-md-offset-1">
        <%= form_for [@restaurant, @comment] do |f| %>
          <div class="form-group">
            <%= f.text_area :content, placeholder: "留個言吧！", class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.submit "Create Comment", class: "btn btn-primary" %>
            <%= f.button "Cancel", type: :reset, class: "btn btn-default" %>
            <%= link_to 'Back to Restaurants', restaurants_path %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_restaurant_list.html.erb
<% @restaurants.each do |restaurant| %>
  <div class="col-sm-6 col-md-4">
    <div class="restaurant-item">
      <%= image_tag restaurant.image, class: "img-responsive center-block" if restaurant.image? %>
      <div class="caption">
        <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
        <p class="label label-default"><%= restaurant.category.name %></p>
        <p><%= truncate(restaurant.description, length: 80) %></p>
      </div>
    </div>
  </div>
<% end %>
<div class="center">
  <%= paginate @restaurants %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1 class="center">Edit Profile</h1>
      <%= form_for @user do |f| %>
      <div class="form-group">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :intro, "自我介紹" %>
        <%= f.text_area :intro, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :avatar, "大頭貼" %>
        <%= f.file_field :avatar %>
      </div>
      <div class="form-group">
        <%= f.submit "Update Profile", class: "btn btn-primary" %>
        <%= f.button "Cancel", type: :reset, class: "btn btn-default" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="page-header">
        <div class="col-md-3 col-sm-4">
          <%= image_tag @user.avatar, width: "200px" if @user.avatar? %>
        </div>
        <div class="col-md-9 col-sm-8">
          <h3><%= @user.name %></h3>
          <p><%= @user.email %></p>
          <p><%= simple_format @user.intro %></p>
          <% if current_user == @user %>
            <%= link_to 'Edit Profile', edit_user_path(@user), class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><stong><%= @commented_restaurants.count %></stong>則已評論過的餐廳</h3>
        </div>
        <div class="panel-body">
          <% @commented_restaurants.each do |restaurant| %>
            <%= link_to restaurant_path(restaurant) do %>
              <div class="my-restaurant">
                <div>
                  <%= image_tag restaurant.image, class: "img-responsive img-rounded" %>
                </div>
                <h5><%= restaurant.name %></h5>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>